Missing "extendr" dependency
error: Something went wrong with the action
error: An error occured: 
Error: Cannot find module 'extendr'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at LivereloadPlugin.serverAfter ([..]/node_modules/docpad-plugin-livereload/out/livereload.plugin.js:65:19)